services:
  - name: recipe-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -b 0.0.0.0:$PORT run:create_app()
    envVars:
      PYTHONUNBUFFERED: "1"
      FLASK_ENV: production
    routes:
      - path: /
        command: python run.py
